- name: Instalacion de Postgre
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql-server 
    - postgresql-contrib
- command: postgresql-setup initdb
- command: systemctl start postgresql
- command: systemctl enable postgresql