#### Ubuntu ####
- name: Actualizar los paquetes a la última actualización
  apt:
    name: "*"
    state: latest
    force_apt_get: True
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Instalacion de packetes requeridos
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Agrega GPG Key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Agregar repositorio 
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
### Centos Redhat ###
- name: Instalacion de packetes requeridos en Centos-Redhat
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Agregar repositorio Centos-Redhat
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
#######
- name: Instalación Docker CE
  package:
    name: docker-ce
- name: User
  shell: usermod -aG docker $(whoami)
- name: Enable Docker Service
  command: systemctl enable docker.service
- name: Start Docker
  command: systemctl start docker.service