- name: Instalacion de Ansible
  yum:
    name: ansible
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- apt:
    name: ansible
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'