- name: Instalacion de packetes requeridos
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc-c++ 
    - make
  ignore_errors: yes
- name: 
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -
- name: Instalaci√≥n de NodeJS
  yum:
    name: nodejs
    state: latest
