- name: upgrade all packages
  apt:
    name: '*'
    state: latest
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "Redhat"
- name: Instalacion de packetes requeridos
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - make
    - gcc-c++ 
  ignore_errors: yes
- shell: "curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -"
  ignore_errors: yes
- name: Instalaci√≥n de NodeJS
  package:
    name: nodejs
    state: latest
  ignore_errors: yes
  